name       : perl-test-file
version    : '1.992'
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Test-File-1.992.tar.gz : 77c57c47a40df11e55d3264608703a79573f909b6f989ef1a1d17f9165680f77
homepage   : https://metacpan.org/pod/Test::File
license    : Artistic-2.0
component  : programming.perl
summary    : Test::File - test file attributes
description: |
    This modules provides a collection of test utilities for file attributes. Some file attributes depend on the owner of the process testing the file in the same way the file test operators do. For instance, root (or super-user or Administrator) may always be able to read files no matter the permissions.
builddeps  :
    - perl-test-pod
    - perl-test-pod-coverage
    - perl-test-utf8
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
