name       : perl-test-file
version    : 1.443
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Test-File-1.443.tar.gz : 61b4a6ab8f617c8c7b5975164cf619468dc304b6baaaea3527829286fa58bcd5
license    : Artistic-2.0
component  : programming.perl
summary    : Test::File - test file attributes
description: |
    Test::File - test file attributes
builddeps  :
    - perl-test-pod
    - perl-test-pod-coverage
    - perl-test-utf8
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
